import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Notifications from "./components/Notifications";
import AuthSession from "./components/AuthSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthSession>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          <Notifications />
        </body>
      </html>
    </AuthSession>
  );
}
